# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sylvain/Programmation/Casio/Utils/casio-emu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sylvain/Programmation/Casio/Utils/casio-emu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sylvain/Programmation/Casio/Utils/casio-emu/CMakeFiles /home/sylvain/Programmation/Casio/Utils/casio-emu//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sylvain/Programmation/Casio/Utils/casio-emu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named calcemu

# Build rule for target.
calcemu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calcemu
.PHONY : calcemu

# fast build rule for target.
calcemu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/build
.PHONY : calcemu/fast

#=============================================================================
# Target rules for targets named calcemu_autogen

# Build rule for target.
calcemu_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calcemu_autogen
.PHONY : calcemu_autogen

# fast build rule for target.
calcemu_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu_autogen.dir/build.make CMakeFiles/calcemu_autogen.dir/build
.PHONY : calcemu_autogen/fast

calcemu_autogen/mocs_compilation.o: calcemu_autogen/mocs_compilation.cpp.o
.PHONY : calcemu_autogen/mocs_compilation.o

# target to build an object file
calcemu_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/calcemu_autogen/mocs_compilation.cpp.o
.PHONY : calcemu_autogen/mocs_compilation.cpp.o

calcemu_autogen/mocs_compilation.i: calcemu_autogen/mocs_compilation.cpp.i
.PHONY : calcemu_autogen/mocs_compilation.i

# target to preprocess a source file
calcemu_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/calcemu_autogen/mocs_compilation.cpp.i
.PHONY : calcemu_autogen/mocs_compilation.cpp.i

calcemu_autogen/mocs_compilation.s: calcemu_autogen/mocs_compilation.cpp.s
.PHONY : calcemu_autogen/mocs_compilation.s

# target to generate assembly for a file
calcemu_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/calcemu_autogen/mocs_compilation.cpp.s
.PHONY : calcemu_autogen/mocs_compilation.cpp.s

src/gui/qt/gui.o: src/gui/qt/gui.cpp.o
.PHONY : src/gui/qt/gui.o

# target to build an object file
src/gui/qt/gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/gui/qt/gui.cpp.o
.PHONY : src/gui/qt/gui.cpp.o

src/gui/qt/gui.i: src/gui/qt/gui.cpp.i
.PHONY : src/gui/qt/gui.i

# target to preprocess a source file
src/gui/qt/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/gui/qt/gui.cpp.i
.PHONY : src/gui/qt/gui.cpp.i

src/gui/qt/gui.s: src/gui/qt/gui.cpp.s
.PHONY : src/gui/qt/gui.s

# target to generate assembly for a file
src/gui/qt/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/gui/qt/gui.cpp.s
.PHONY : src/gui/qt/gui.cpp.s

src/hardware/cpuRegisters/cpuRegisters.o: src/hardware/cpuRegisters/cpuRegisters.c.o
.PHONY : src/hardware/cpuRegisters/cpuRegisters.o

# target to build an object file
src/hardware/cpuRegisters/cpuRegisters.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/cpuRegisters/cpuRegisters.c.o
.PHONY : src/hardware/cpuRegisters/cpuRegisters.c.o

src/hardware/cpuRegisters/cpuRegisters.i: src/hardware/cpuRegisters/cpuRegisters.c.i
.PHONY : src/hardware/cpuRegisters/cpuRegisters.i

# target to preprocess a source file
src/hardware/cpuRegisters/cpuRegisters.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/cpuRegisters/cpuRegisters.c.i
.PHONY : src/hardware/cpuRegisters/cpuRegisters.c.i

src/hardware/cpuRegisters/cpuRegisters.s: src/hardware/cpuRegisters/cpuRegisters.c.s
.PHONY : src/hardware/cpuRegisters/cpuRegisters.s

# target to generate assembly for a file
src/hardware/cpuRegisters/cpuRegisters.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/cpuRegisters/cpuRegisters.c.s
.PHONY : src/hardware/cpuRegisters/cpuRegisters.c.s

src/hardware/display/display.o: src/hardware/display/display.c.o
.PHONY : src/hardware/display/display.o

# target to build an object file
src/hardware/display/display.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/display/display.c.o
.PHONY : src/hardware/display/display.c.o

src/hardware/display/display.i: src/hardware/display/display.c.i
.PHONY : src/hardware/display/display.i

# target to preprocess a source file
src/hardware/display/display.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/display/display.c.i
.PHONY : src/hardware/display/display.c.i

src/hardware/display/display.s: src/hardware/display/display.c.s
.PHONY : src/hardware/display/display.s

# target to generate assembly for a file
src/hardware/display/display.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/display/display.c.s
.PHONY : src/hardware/display/display.c.s

src/hardware/dma/dma.o: src/hardware/dma/dma.c.o
.PHONY : src/hardware/dma/dma.o

# target to build an object file
src/hardware/dma/dma.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/dma/dma.c.o
.PHONY : src/hardware/dma/dma.c.o

src/hardware/dma/dma.i: src/hardware/dma/dma.c.i
.PHONY : src/hardware/dma/dma.i

# target to preprocess a source file
src/hardware/dma/dma.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/dma/dma.c.i
.PHONY : src/hardware/dma/dma.c.i

src/hardware/dma/dma.s: src/hardware/dma/dma.c.s
.PHONY : src/hardware/dma/dma.s

# target to generate assembly for a file
src/hardware/dma/dma.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/dma/dma.c.s
.PHONY : src/hardware/dma/dma.c.s

src/hardware/intc/intc.o: src/hardware/intc/intc.c.o
.PHONY : src/hardware/intc/intc.o

# target to build an object file
src/hardware/intc/intc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/intc/intc.c.o
.PHONY : src/hardware/intc/intc.c.o

src/hardware/intc/intc.i: src/hardware/intc/intc.c.i
.PHONY : src/hardware/intc/intc.i

# target to preprocess a source file
src/hardware/intc/intc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/intc/intc.c.i
.PHONY : src/hardware/intc/intc.c.i

src/hardware/intc/intc.s: src/hardware/intc/intc.c.s
.PHONY : src/hardware/intc/intc.s

# target to generate assembly for a file
src/hardware/intc/intc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/intc/intc.c.s
.PHONY : src/hardware/intc/intc.c.s

src/hardware/keyboard/keyboard.o: src/hardware/keyboard/keyboard.c.o
.PHONY : src/hardware/keyboard/keyboard.o

# target to build an object file
src/hardware/keyboard/keyboard.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/keyboard/keyboard.c.o
.PHONY : src/hardware/keyboard/keyboard.c.o

src/hardware/keyboard/keyboard.i: src/hardware/keyboard/keyboard.c.i
.PHONY : src/hardware/keyboard/keyboard.i

# target to preprocess a source file
src/hardware/keyboard/keyboard.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/keyboard/keyboard.c.i
.PHONY : src/hardware/keyboard/keyboard.c.i

src/hardware/keyboard/keyboard.s: src/hardware/keyboard/keyboard.c.s
.PHONY : src/hardware/keyboard/keyboard.s

# target to generate assembly for a file
src/hardware/keyboard/keyboard.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/keyboard/keyboard.c.s
.PHONY : src/hardware/keyboard/keyboard.c.s

src/hardware/power/power.o: src/hardware/power/power.c.o
.PHONY : src/hardware/power/power.o

# target to build an object file
src/hardware/power/power.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/power/power.c.o
.PHONY : src/hardware/power/power.c.o

src/hardware/power/power.i: src/hardware/power/power.c.i
.PHONY : src/hardware/power/power.i

# target to preprocess a source file
src/hardware/power/power.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/power/power.c.i
.PHONY : src/hardware/power/power.c.i

src/hardware/power/power.s: src/hardware/power/power.c.s
.PHONY : src/hardware/power/power.s

# target to generate assembly for a file
src/hardware/power/power.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/power/power.c.s
.PHONY : src/hardware/power/power.c.s

src/hardware/rtc/rtc.o: src/hardware/rtc/rtc.c.o
.PHONY : src/hardware/rtc/rtc.o

# target to build an object file
src/hardware/rtc/rtc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/rtc/rtc.c.o
.PHONY : src/hardware/rtc/rtc.c.o

src/hardware/rtc/rtc.i: src/hardware/rtc/rtc.c.i
.PHONY : src/hardware/rtc/rtc.i

# target to preprocess a source file
src/hardware/rtc/rtc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/rtc/rtc.c.i
.PHONY : src/hardware/rtc/rtc.c.i

src/hardware/rtc/rtc.s: src/hardware/rtc/rtc.c.s
.PHONY : src/hardware/rtc/rtc.s

# target to generate assembly for a file
src/hardware/rtc/rtc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/rtc/rtc.c.s
.PHONY : src/hardware/rtc/rtc.c.s

src/hardware/timers/timers.o: src/hardware/timers/timers.c.o
.PHONY : src/hardware/timers/timers.o

# target to build an object file
src/hardware/timers/timers.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/timers/timers.c.o
.PHONY : src/hardware/timers/timers.c.o

src/hardware/timers/timers.i: src/hardware/timers/timers.c.i
.PHONY : src/hardware/timers/timers.i

# target to preprocess a source file
src/hardware/timers/timers.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/timers/timers.c.i
.PHONY : src/hardware/timers/timers.c.i

src/hardware/timers/timers.s: src/hardware/timers/timers.c.s
.PHONY : src/hardware/timers/timers.s

# target to generate assembly for a file
src/hardware/timers/timers.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/timers/timers.c.s
.PHONY : src/hardware/timers/timers.c.s

src/hardware/tlb/tlb.o: src/hardware/tlb/tlb.c.o
.PHONY : src/hardware/tlb/tlb.o

# target to build an object file
src/hardware/tlb/tlb.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/tlb/tlb.c.o
.PHONY : src/hardware/tlb/tlb.c.o

src/hardware/tlb/tlb.i: src/hardware/tlb/tlb.c.i
.PHONY : src/hardware/tlb/tlb.i

# target to preprocess a source file
src/hardware/tlb/tlb.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/tlb/tlb.c.i
.PHONY : src/hardware/tlb/tlb.c.i

src/hardware/tlb/tlb.s: src/hardware/tlb/tlb.c.s
.PHONY : src/hardware/tlb/tlb.s

# target to generate assembly for a file
src/hardware/tlb/tlb.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/hardware/tlb/tlb.c.s
.PHONY : src/hardware/tlb/tlb.c.s

src/instructions.o: src/instructions.c.o
.PHONY : src/instructions.o

# target to build an object file
src/instructions.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/instructions.c.o
.PHONY : src/instructions.c.o

src/instructions.i: src/instructions.c.i
.PHONY : src/instructions.i

# target to preprocess a source file
src/instructions.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/instructions.c.i
.PHONY : src/instructions.c.i

src/instructions.s: src/instructions.c.s
.PHONY : src/instructions.s

# target to generate assembly for a file
src/instructions.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/instructions.c.s
.PHONY : src/instructions.c.s

src/interpreter.o: src/interpreter.c.o
.PHONY : src/interpreter.o

# target to build an object file
src/interpreter.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/interpreter.c.o
.PHONY : src/interpreter.c.o

src/interpreter.i: src/interpreter.c.i
.PHONY : src/interpreter.i

# target to preprocess a source file
src/interpreter.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/interpreter.c.i
.PHONY : src/interpreter.c.i

src/interpreter.s: src/interpreter.c.s
.PHONY : src/interpreter.s

# target to generate assembly for a file
src/interpreter.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/interpreter.c.s
.PHONY : src/interpreter.c.s

src/interrupts.o: src/interrupts.c.o
.PHONY : src/interrupts.o

# target to build an object file
src/interrupts.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/interrupts.c.o
.PHONY : src/interrupts.c.o

src/interrupts.i: src/interrupts.c.i
.PHONY : src/interrupts.i

# target to preprocess a source file
src/interrupts.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/interrupts.c.i
.PHONY : src/interrupts.c.i

src/interrupts.s: src/interrupts.c.s
.PHONY : src/interrupts.s

# target to generate assembly for a file
src/interrupts.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/interrupts.c.s
.PHONY : src/interrupts.c.s

src/memory/memory.o: src/memory/memory.c.o
.PHONY : src/memory/memory.o

# target to build an object file
src/memory/memory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/memory/memory.c.o
.PHONY : src/memory/memory.c.o

src/memory/memory.i: src/memory/memory.c.i
.PHONY : src/memory/memory.i

# target to preprocess a source file
src/memory/memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/memory/memory.c.i
.PHONY : src/memory/memory.c.i

src/memory/memory.s: src/memory/memory.c.s
.PHONY : src/memory/memory.s

# target to generate assembly for a file
src/memory/memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/memory/memory.c.s
.PHONY : src/memory/memory.c.s

src/memory/specialAddrs.o: src/memory/specialAddrs.c.o
.PHONY : src/memory/specialAddrs.o

# target to build an object file
src/memory/specialAddrs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/memory/specialAddrs.c.o
.PHONY : src/memory/specialAddrs.c.o

src/memory/specialAddrs.i: src/memory/specialAddrs.c.i
.PHONY : src/memory/specialAddrs.i

# target to preprocess a source file
src/memory/specialAddrs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/memory/specialAddrs.c.i
.PHONY : src/memory/specialAddrs.c.i

src/memory/specialAddrs.s: src/memory/specialAddrs.c.s
.PHONY : src/memory/specialAddrs.s

# target to generate assembly for a file
src/memory/specialAddrs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calcemu.dir/build.make CMakeFiles/calcemu.dir/src/memory/specialAddrs.c.s
.PHONY : src/memory/specialAddrs.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... calcemu_autogen"
	@echo "... calcemu"
	@echo "... calcemu_autogen/mocs_compilation.o"
	@echo "... calcemu_autogen/mocs_compilation.i"
	@echo "... calcemu_autogen/mocs_compilation.s"
	@echo "... src/gui/qt/gui.o"
	@echo "... src/gui/qt/gui.i"
	@echo "... src/gui/qt/gui.s"
	@echo "... src/hardware/cpuRegisters/cpuRegisters.o"
	@echo "... src/hardware/cpuRegisters/cpuRegisters.i"
	@echo "... src/hardware/cpuRegisters/cpuRegisters.s"
	@echo "... src/hardware/display/display.o"
	@echo "... src/hardware/display/display.i"
	@echo "... src/hardware/display/display.s"
	@echo "... src/hardware/dma/dma.o"
	@echo "... src/hardware/dma/dma.i"
	@echo "... src/hardware/dma/dma.s"
	@echo "... src/hardware/intc/intc.o"
	@echo "... src/hardware/intc/intc.i"
	@echo "... src/hardware/intc/intc.s"
	@echo "... src/hardware/keyboard/keyboard.o"
	@echo "... src/hardware/keyboard/keyboard.i"
	@echo "... src/hardware/keyboard/keyboard.s"
	@echo "... src/hardware/power/power.o"
	@echo "... src/hardware/power/power.i"
	@echo "... src/hardware/power/power.s"
	@echo "... src/hardware/rtc/rtc.o"
	@echo "... src/hardware/rtc/rtc.i"
	@echo "... src/hardware/rtc/rtc.s"
	@echo "... src/hardware/timers/timers.o"
	@echo "... src/hardware/timers/timers.i"
	@echo "... src/hardware/timers/timers.s"
	@echo "... src/hardware/tlb/tlb.o"
	@echo "... src/hardware/tlb/tlb.i"
	@echo "... src/hardware/tlb/tlb.s"
	@echo "... src/instructions.o"
	@echo "... src/instructions.i"
	@echo "... src/instructions.s"
	@echo "... src/interpreter.o"
	@echo "... src/interpreter.i"
	@echo "... src/interpreter.s"
	@echo "... src/interrupts.o"
	@echo "... src/interrupts.i"
	@echo "... src/interrupts.s"
	@echo "... src/memory/memory.o"
	@echo "... src/memory/memory.i"
	@echo "... src/memory/memory.s"
	@echo "... src/memory/specialAddrs.o"
	@echo "... src/memory/specialAddrs.i"
	@echo "... src/memory/specialAddrs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

